# Generated by Django 4.2.16 on 2024-09-27 07:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="categories",
            table="category",
        ),
    ]
